# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\materials\projects\HEQPY\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableForSolution = QtWidgets.QTableWidget(self.centralwidget)
        self.tableForSolution.setGeometry(QtCore.QRect(10, 100, 781, 461))
        self.tableForSolution.setObjectName("tableForSolution")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 311, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 311, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 311, 16))
        self.label_3.setObjectName("label_3")
        self.buildSolution = QtWidgets.QPushButton(self.centralwidget)
        self.buildSolution.setGeometry(QtCore.QRect(460, 2, 331, 91))
        self.buildSolution.setObjectName("buildSolution")
        self.lineEditForN = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForN.setGeometry(QtCore.QRect(330, 10, 113, 20))
        self.lineEditForN.setObjectName("lineEditForN")
        self.lineEditForM = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForM.setGeometry(QtCore.QRect(330, 40, 113, 20))
        self.lineEditForM.setObjectName("lineEditForM")
        self.lineEditForT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForT.setGeometry(QtCore.QRect(330, 70, 113, 20))
        self.lineEditForT.setObjectName("lineEditForT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите число разбиений по пространственной переменной"))
        self.label_2.setText(_translate("MainWindow", "Введите число разбиений по времени"))
        self.label_3.setText(_translate("MainWindow", "Введите правую границу промежутка времени"))
        self.buildSolution.setText(_translate("MainWindow", "Построить решение"))
